### ISSUE TITLE
Патчер не работает с загруженными mp3 на Яндекс.Музыку

### ISSUE THREAD

**Issue by donelofficial** [PulseSync-Official/YMusic-DRPC#40]
При попытке проигрывания своих mp3, загруженных на Яндекс.Музыку, в дискорде ничего не отображается, а в консоль выпадает ошибка:
```
(node:20948) UnhandledPromiseRejectionWarning: Error: child "activity" fails because [child "buttons" fails because ["buttons" must be an array]]
    at RPCClient._onRpcMessage (C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\node_modules\discord-rpc\src\client.js:178:19)
    at IPCTransport.emit (node:events:514:28)
    at C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:514:28)
    at emitReadable_ (node:internal/streams/readable:641:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:20948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

С треками, которые официально доступны на Яндекс.Музыке, такой проблемы нет.

**Comment by Maks1mio** [comment]
Да есть такое, в ближайшее время когда обновим приложение на electron ts с exe, будет исправлено

**Comment by Maks1mio** [comment]
Ближайший анонс будет в дискорде

**Comment by foreA-adoxid** [comment]
Исправлено в новой версии. Подробности в дискорде

**Comment by Maks1mio** [comment]
Речь идет о ветке которую скоро релизнем.
